# Jekyll configuration precedence:
# 1. Gruntfile task
# 3. config.yml

name: MRGS/SLMR
description: Mount Royal Game Society / Société ludique du Mont-Royal
author:
  name: MRGS/SLMR
  email: bakedgoods@mrgs.ca

prose:
  siteurl: "http://mrgs.github.io/"
  media: "media"

defaults:
  -
    scope:
      path: "" # empty string for all files
      type: "post"
    values:
      layout: "post"

excerpt_separator: <hr />

baseurl: ''
oldwpdir: 'old-wordpress-files'

paginate: 5

exclude: ['_bower_components', 'node_modules', '.git',
	'Gemfile*', 'bower.json', 'package.json', '*.sublime*',
  'gulpfile.*', 'README.*']

include: ['.htaccess']

permalink: pretty
future: false
show_drafts: false

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlights: none
